name: Check Single Line PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_single_line:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR for single line change
        run: |
          for file in $(git diff --name-only HEAD^); do
            line_count=$(git diff HEAD^ HEAD $file | grep '^[+-]' | grep -v '^\s*[-+]\s*$' | wc -l)
            if [ "$line_count" -gt 1 ]; then
              echo "Error: $file has more than one line changed. Please make only one-line changes per PR."
              exit 1
            fi
          done
